### PR TITLE
Fix modified_ast issue

### LINKED ISSUE #108: Defining a type called `error()` leads to `modified_ast` error in some cases
The following file leads to a parsing error:

```erlang
-module(test).
-type error() :: x.
```

The error I get is the following:

```
===> Error parsing files: {modified_ast,"test.erl","test.erl"}
Stack: [{rebar3_formatter,format,3,
                          [{file,"/tmp/test/_build/default/plugins/rebar3_format/src/rebar3_formatter.erl"},
                           {line,40}]},
        {rebar3_format_prv,'-format/3-fun-0-',3,
                           [{file,"/tmp/test/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,112}]},
        {lists,'-filter/2-lc$^0/1-0-',2,[{file,"lists.erl"},{line,1286}]},
        {rebar3_format_prv,format,3,
                           [{file,"/tmp/test/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,110}]},
        {rebar3_format_prv,do,1,
                           [{file,"tmp/test/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,41}]},
        {rebar_core,do,2,
                    [{file,"/tmp/cirrus-ci-build/src/rebar_core.erl"},
                     {line,154}]},
        {rebar3,run_aux,2,
                [{file,"/tmp/cirrus-ci-build/src/rebar3.erl"},{line,182}]},
        {rebar3,main,1,
                [{file,"/tmp/cirrus-ci-build/src/rebar3.erl"},{line,66}]}]
===> Unknown Formatting Error: {modified_ast,"test.erl","test.erl"}
```

However, it does actually succeed in formatting the file, and inserts the required newline:

```erlang
-module(test).

-type error() :: x.
```

Running `rebar3 format` again on the formatted file does not trigger this error.

### PR DESCRIPTION
**Pull request by juanbono**
This PR aims to fix #108 .

### CODE REVIEW

**Comment by juanbono** [comment]
Debugging a bit i saw that the issue was when removing the line numbers, here are both ASTs from the test files I added:
```erlang
%% Original AST
 [{attribute,no,module,test},
  {attribute,no,type,{error,{atom,2,x},[]}},
  {attribute,no,spec,{{a_fun,0},no}},
  {function,no,a_fun,0,[{clause,no,[],[],[{atom,no,x}]}]}]

%% AST after formatting (there is a newline added)
 [{attribute,no,module,test},
  {attribute,no,type,{error,{atom,3,x},[]}},
  {attribute,no,spec,{{a_fun,0},no}},
  {function,no,a_fun,0,[{clause,no,[],[],[{atom,no,x}]}]}]
```

File: src/rebar3_formatter.erl [hunk 1]
```diff
@@ -68,12 +68,7 @@ remove_line_numbers(AST) when is_list(AST) ->
     lists:map(fun remove_line_numbers/1, AST);
 remove_line_numbers(AST) when is_tuple(AST) ->
     [Type, _Line | Rest] = tuple_to_list(AST),
-    case Type of
```
Comment (elbrujohalcon) [inline src/rebar3_formatter.erl:71]: Wait… what if there is an actual error when parsing the file?
