### PR TITLE
Fixes #249: Spacing for empty records

### LINKED ISSUE #249: Weird spacing for empty record
**Describe the bug**
An empty record definition, combined with option `spaces_around_fields => true`, gets formatted unexpectedly as `#rec{ 
 }` (there's two spaces there, but GitHub doesn't render them).

**To Reproduce**
Define a record as `#rec{}`.

**Expected behavior**
After formatting I expect nothing to change.

**Rebar3 Log**
Not required.

**Additional context**
It might be happening for the other elements to which the option applies 😄, but I guess one fix will fix them all.

### PR DESCRIPTION
**Pull request by vkatsuba**
Fixes #249. Small fix, but was also need to update `test_app`...

### CODE REVIEW

**Comment by vkatsuba** [comment]
Nested records in fields of record have the same issue, PR in **WIP**.

File: src/formatters/default_formatter.erl [hunk 1]
```diff
@@ -646,8 +646,13 @@ lay_no_comments(Node, Ctxt) ->
             Ctxt1 = reset_prec(Ctxt),
             D1 = beside(beside(lay_text_float("#"), lay(erl_syntax:record_expr_type(Node), Ctxt1)),
                         text("{")),
-            D2 = lay_fields(D1, erl_syntax:record_expr_fields(Node), Ctxt1, fun lay/2),
             Arg = erl_syntax:record_expr_argument(Node),
+            D2 = case Arg of
```
Comment (elbrujohalcon) [inline src/formatters/default_formatter.erl:650]: Why are you branching on `Arg` being `none`?
I mean… the request of not adding space between `{` and `}` should apply even if you write `AVar#a_record{}`.
No idea why anybody would do that… but it's perfectly valid Erlang syntax.
Maybe it would be better to do `case erl_syntax:record_expr_fields(Node) of [] -> …; Fields -> … end`, instead.

File: test/test_app_SUITE.erl [hunk 2]
```diff
@@ -21,7 +21,8 @@ test_app(_Config) ->
             _ ->
                 {ignore, ["src/*_ignore.erl", "src/ignored_file_config.erl", "src/otp23.erl"]}
         end,
-    State2 = rebar_state:set(State1, format, [Files, IgnoredFiles]),
+    Options = {options, #{spaces_around_fields => true}},
```
Comment (elbrujohalcon) [inline test/test_app_SUITE.erl:24]: Why is this option needed here? I think that the default (`false`) is ok for tests.

**Review by elbrujohalcon — CHANGES_REQUESTED** [review]
I'm not sure why you added `#{spaces_around_fields => true}` to all tests.
When we need that for a particular test, we add it only to the module that we want to test, e.g. …

```erlang
-format #{spaces_around_fields => true}.
```

**Comment by elbrujohalcon** [comment]
> @elbrujohalcon the nested records in fields of record have the same issue, PR in **WIP**. Please see `records.erl`, I was add:
> 
> ```
> -record(rec, {}).
> -record(rec_empty, #rec{}).
> ```
> 
> and current fix working as expected, but...
> `-record(record, {with_another :: #record{}, in_it}).` have the same issue, still in investigation.

Yeah. I think this is related to the `case` statement I mentioned in https://github.com/AdRoll/rebar3_format/pull/256#discussion_r627368632

File: src/formatters/default_formatter.erl [hunk 3]
```diff
@@ -646,7 +646,12 @@ lay_no_comments(Node, Ctxt) ->
             Ctxt1 = reset_prec(Ctxt),
             D1 = beside(beside(lay_text_float("#"), lay(erl_syntax:record_expr_type(Node), Ctxt1)),
                         text("{")),
-            D2 = lay_fields(D1, erl_syntax:record_expr_fields(Node), Ctxt1, fun lay/2),
+            D2 = case erl_syntax:record_expr_fields(Node) of
+                [] ->
+                    lay_fields(D1, [], Ctxt1#ctxt{spaces_around_fields = false}, fun lay/2);
```
Comment (elbrujohalcon) [inline src/formatters/default_formatter.erl:651]:
```suggestion
                    par([D1,lay_text_float("}")]);
```
Didn't test it, but since there are no fields, it's probably what `lay_fields/4` will do, anyway.

**Review by elbrujohalcon — CHANGES_REQUESTED** [review]
A slight simplification.

**Comment by vkatsuba** [comment]
@elbrujohalcon looks like I was find more elegant way, please take a look.

**Review by elbrujohalcon — APPROVED** [review]
Love it! The final version is excellent.
Thank you very much, @vkatsuba !!
