### PR TITLE
Fix #59: Indent try body

### LINKED ISSUE #59: add a break after "try" for multiline try/catch blocks
this
```erl
    try CpmMicros = DecodedCost#coinpurse_result.cpm_micros,
        TotalPreMargin = calculate_prepostmargin(PreMargin),
        TotalCommission = calculate_commission(Commission, Percent),
        DecodedCost#coinpurse_result{cost_cpm_micros = Result}
    catch
      E:R:StackTrace ->
          DecodedCost#coinpurse_result{cost_calculation_error = {E, R, StackTrace}}
    end.
```

should be
```erl
    try 
        CpmMicros = DecodedCost#coinpurse_result.cpm_micros,
        TotalPreMargin = calculate_prepostmargin(PreMargin),
        TotalCommission = calculate_commission(Commission, Percent),
        DecodedCost#coinpurse_result{cost_cpm_micros = Result}
    catch
      E:R:StackTrace ->
          DecodedCost#coinpurse_result{cost_calculation_error = {E, R, StackTrace}}
    end.
```

### PR DESCRIPTION
**Pull request by elbrujohalcon**

### CODE REVIEW

File: src/rebar3_format_prv.erl [hunk 1]
```diff
@@ -81,11 +81,12 @@ get_opts(State) -> proplists:get_value(options, rebar_state:get(State, format, [
                                                                           {error,
                                                                            {atom(), string()}}.
 format(Files, Formatter, Opts) ->
-    try lists:foreach(fun (File) ->
-                              rebar_api:debug("Formatting ~p with ~p", [File, Opts]),
-                              rebar3_formatter:format(File, Formatter, Opts)
-                      end,
-                      Files)
+    try
+      lists:foreach(fun (File) ->
```
Comment (diegomanuel) [inline src/rebar3_format_prv.erl]: Missing 2 more indentation spaces here?

Comment (elbrujohalcon) [reply src/rebar3_format_prv.erl]: I used `sub-indent` like with the `after` block.
