### PR TITLE
[#280] Fix #280: Handle space-terminated strings

### LINKED ISSUE #280: Error handling multiline strings with lines containing trailing spaces
### Describe the bug
Code is compiled and runs completely as it was expected. While formatting we get an error.

###  To Reproduce
Run that code:
```erlang
-module(recipe_15).

-export([]).

%%
%% Tests
%%
-ifdef(TEST).

-include_lib("eunit/include/eunit.hrl").


research_test_() ->
    {"Prevent Runaway Repetition",
     {foreach,
      local,
      fun build_text_and_expectation/0,
      [fun research_01/1,
       fun research_02/1]}}.

build_text_and_expectation()->
        Text="
<!DOCTYPE html>
<html>
<head>
    <meta charset=\"UTF-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
	",
	
	Expected = "<html>\n<head>\n    <meta charset=\"UTF-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Document</title>\n</head>\n<body>\n    \n</body>\n</html>",
	{Text, Expected}.

research_01({Text, Expected})->
	Regex = "<html>(?>.*?<head>)(?>.*?<title>)(?>.*?</title>)(?>.*?</head>)(?>.*?<body[^>]*>)(?>.*?</body>).*?</html>",
	{ok, MP} = re:compile(Regex,[caseless, multiline,dotall]),
    %Result = re:run(Text, MP, [{capture, first, list}]),
	{match, [Result]} = re:run(Text, MP, [{capture, first, list}]),
    %?debugFmt("~p~n",[Result]).
    ?_assertEqual(Expected, Result).

research_02({Text, Expected})->
    Regex = "<html>.*?<head>.*?<title>.*?</title>.*?</head>.*?<body[^>]*>.*?</body>.*?</html>",
	{ok, MP} = re:compile(Regex,[caseless, multiline,dotall]),
    %Result = re:run(Text, MP, [{capture, first, list}]),
	{match, [Result]} = re:run(Text, MP, [{capture, first, list}]),
    %?debugFmt("~p~n",[Result]).
    ?_assertEqual(Expected, Result).

-endif.
```

### Expected behavior
Formatting action adds \t inside a multiline test.

### Rebar3 Log
```bash
H:\books1\regular expression\regex\Regular Expressions Cookbook 2nd\github\code\ch02\basic>rebar3 f
ormat
===> Error parsing files: {modified_ast,"lib/recipe_15/src/recipe_15.erl",
                              "lib/recipe_15/src/recipe_15.erl"}
Stack: [{rebar3_ast_formatter,format,3,
                              [{file,"h:/books1/regular expression/regex/Regular Expressions Cookbo
ok 2nd/github/code/ch02/basic/_build/default/plugins/rebar3_format/src/rebar3_ast_formatter.erl"},
                               {line,40}]},
        {rebar3_format_prv,'-format_files/2-fun-0-',2,
                           [{file,"h:/books1/regular expression/regex/Regular Expressions Cookbook
2nd/github/code/ch02/basic/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,125}]},
        {lists,'-filter/2-lc$^0/1-0-',2,[{file,"lists.erl"},{line,1290}]},
        {rebar3_format_prv,format_files,2,
                           [{file,"h:/books1/regular expression/regex/Regular Expressions Cookbook
2nd/github/code/ch02/basic/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,123}]},
        {rebar3_format_prv,do,1,
                           [{file,"h:/books1/regular expression/regex/Regular Expressions Cookbook
2nd/github/code/ch02/basic/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,43}]},
        {rebar_core,do,2,
                    [{file,"/home/runner/work/rebar3/rebar3/src/rebar_core.erl"},
                     {line,155}]},
        {rebar3,run_aux,2,
                [{file,"/home/runner/work/rebar3/rebar3/src/rebar3.erl"},
                 {line,182}]},
        {rebar3,main,1,
                [{file,"/home/runner/work/rebar3/rebar3/src/rebar3.erl"},
                 {line,66}]}]
=ERROR REPORT==== 27-Aug-2021::17:18:14.949000 ===
    modified_ast: lib/recipe_15/src/recipe_15.erl
    removed: [{function,no,build_text_and_expectation,0,
                  [{clause,no,[],[],
                       [{match,no,
                            {var,no,'Text'},
                            {string,no,
                                "\n<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"UTF-8\">\n
   <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\
"width=device-width, initial-scale=1.0\">\n    <title>Document</title>\n</head>\n<body>\n    \n</bo
dy>\n</html>\n\t"}},
                        {match,no,
                            {var,no,'Expected'},
                            {string,no,
                                "<html>\n<head>\n    <meta charset=\"UTF-8\">\n    <meta http-equiv
=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"width=device-width
, initial-scale=1.0\">\n    <title>Document</title>\n</head>\n<body>\n    \n</body>\n</html>"}},
                        {tuple,no,[{var,no,'Text'},{var,no,'Expected'}]}]}]}]
    added: [{function,no,build_text_and_expectation,0,
                [{clause,no,[],[],
                     [{match,no,
                          {var,no,'Text'},
                          {string,no,
                              "\n<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"UTF-8\">\n
 <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"w
idth=device-width, initial-scale=1.0\">\n    <title>Document</title>\n</head>\n<body>\n\n</body>\n<
/html>\n\t"}},
                      {match,no,
                          {var,no,'Expected'},
                          {string,no,
                              "<html>\n<head>\n    <meta charset=\"UTF-8\">\n    <meta http-equiv=\
"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"width=device-width,
initial-scale=1.0\">\n    <title>Document</title>\n</head>\n<body>\n    \n</body>\n</html>"}},
                      {tuple,no,[{var,no,'Text'},{var,no,'Expected'}]}]}]}]
===> Unknown Formatting Error: {modified_ast,"lib/recipe_15/src/recipe_15.erl",
                              "lib/recipe_15/src/recipe_15.erl"}
```

### Additional context
No.

### PR DESCRIPTION
**Pull request by elbrujohalcon**
Fix #280.
Actually, it's sort of a _workaround_ to preserve the semantic value of the string while still being able to trim trailing whitespace from files easily.
I think it's a good tradeoff since, just like not too many people start their multiline strings with tabs, not too many people should finish them with spaces.

### CODE REVIEW

File: src/formatters/default_formatter.erl [hunk 1]
```diff
@@ -1095,11 +1095,19 @@ lay_string_line(S, #ctxt{truncate_strings = true, ribbon = Ribbon}) ->
...
-    %% We need to replace \n\t here as a work around for how remove_tabs/1 works
-    %% It's a hack, but it makes the formatter consistent.
-    %% And it only affect strings that start with tab right after a newline.
-    %% We truly hope that there are not too many of those.
-    text(switch_tabs_after_newline(S)).
+    text(prepare_string_line(S)).
+
+%% @doc We need to replace \n\t here as a work around for how remove_tabs/1 works
+%%      It's a hack, but it makes the formatter consistent.
+%%      And it only affect strings that start with tab right after a newline.
```
Comment (pbrudnick) [inline src/formatters/default_formatter.erl:1102]:
```suggestion
%%      And it only affects strings that start with tab right after a newline.
```

**Review by pbrudnick — APPROVED** [review]
